### PR TITLE
Enable feed forward for OcvPerson

### PR DESCRIPTION
**Pull request by brosenberg42**
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-contrib-components/21)

### CODE REVIEW

**Comment by jrobble** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[cpp/OcvPersonDetection/PersonDetection.cpp, line 228 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-contrib-components/21#-KuuAUio0Bf96pTWQtSC:-KuuAUio0Bf96pTWQtSD:b-dxcbts) ([raw file](https://github.com/openmpf/openmpf-contrib-components/blob/ce7aab5247b01aa2fb1ada06358597444944d665/cpp/OcvPersonDetection/PersonDetection.cpp#L228)):*
> ```cpp
>         cv::Rect imageRect(cv::Point(0, 0), image.size());
>         for (const cv::Rect &detection : found) {
>             cv::Rect intersection = detection & imageRect;
> ```

Makes sense.

---

*[cpp/OcvPersonDetection/PersonDetection.cpp, line 229 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-contrib-components/21#-KuuAx6T-7lOTlFFww3w:-KuuAx6T-7lOTlFFww3x:bsyazfu) ([raw file](https://github.com/openmpf/openmpf-contrib-components/blob/ce7aab5247b01aa2fb1ada06358597444944d665/cpp/OcvPersonDetection/PersonDetection.cpp#L229)):*
> ```cpp
>         for (const cv::Rect &detection : found) {
>             cv::Rect intersection = detection & imageRect;
>             locations.emplace_back(intersection.x, intersection.y, intersection.width, intersection.height);
> ```

Fancy.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-contrib-components/21)*

**Comment by jrobble** [comment]
*[cpp/OcvPersonDetection/tracking/detector.cpp, line 146 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-contrib-components/21#-KuuI-dLWw4hyRrkwXuc:-Kuu9mdevpmrXZPJ7wNR:bkqchnn) ([raw file](https://github.com/openmpf/openmpf-contrib-components/blob/ce7aab5247b01aa2fb1ada06358597444944d665/cpp/OcvPersonDetection/tracking/detector.cpp#L146)):*
> cv::Size padding = extraSpaceNeeded / 2;

As discussed, please use ceiling.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-contrib-components/21)*

**Comment by brosenberg42** [comment]
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[cpp/OcvPersonDetection/tracking/detector.cpp, line 146 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-contrib-components/21#-KuuI-dLWw4hyRrkwXuc:-KuuUqrr9Vrlt8ZIEve_:b-896fix) ([raw file](https://github.com/openmpf/openmpf-contrib-components/blob/ce7aab5247b01aa2fb1ada06358597444944d665/cpp/OcvPersonDetection/tracking/detector.cpp#L146)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

> cv::Size padding = extraSpaceNeeded / 2;

As discussed, please use ceiling.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-contrib-components/21)*

**Comment by jrobble** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-contrib-components/21)*

**Pull request merged**
