### PR TITLE
Make OcvPerson component use auto frame skip

### PR DESCRIPTION
**Pull request by brosenberg42**
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-contrib-components/11)

### CODE REVIEW

**Comment by jrobble** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-contrib-components/11)*

**Comment by jrobble** [comment]
*[cpp/OcvPersonDetection/PersonDetection.cpp, line 390 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-contrib-components/11#-KqzP8-wVQOam6KudI7p:-KqzP8-wVQOam6KudI7q:b77gql) ([raw file](https://github.com/openmpf/openmpf-contrib-components/blob/acad11eda855809d2fc353fc3ae33a1e309bd90c/cpp/OcvPersonDetection/PersonDetection.cpp#L390)):*
> ```cpp
> 
>     //  Open the input video.
>     cv::VideoCapture cap;
> ```

Should we update this function? It's still using the old OpenCV video capture.

To be honest, I think we can remove this function. It's the only component with a debug function like this. It may predate the Markup component. What do you think?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-contrib-components/11)*

**Comment by jrobble** [comment]
Your code fixes a bug. This component did not handle frame intervals correctly before. 

[old.json.txt](https://github.com/openmpf/openmpf-contrib-components/files/1206634/old.json.txt) vs. [new.json.txt](https://github.com/openmpf/openmpf-contrib-components/files/1206633/new.json.txt)

**Comment by brosenberg42** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[cpp/OcvPersonDetection/PersonDetection.cpp, line 390 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-contrib-components/11#-KqzP8-wVQOam6KudI7p:-Kr1d6-xX9J_RaiTUskG:b-js3mvu) ([raw file](https://github.com/openmpf/openmpf-contrib-components/blob/acad11eda855809d2fc353fc3ae33a1e309bd90c/cpp/OcvPersonDetection/PersonDetection.cpp#L390)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Should we update this function? It's still using the old OpenCV video capture.

To be honest, I think we can remove this function. It's the only component with a debug function like this. It may predate the Markup component. What do you think?
</blockquote></details>

I agree, we should remove it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-contrib-components/11)*

**Comment by jrobble** [comment]
*[cpp/OcvPersonDetection/PersonDetection.cpp, line 89 at r2](https://reviewable.io:443/reviews/openmpf/openmpf-contrib-components/11#-Kr1dn8a2dDRBoywyqPH:-Kr1dn8a2dDRBoywyqPI:buxxar2) ([raw file](https://github.com/openmpf/openmpf-contrib-components/blob/17aa673778b4d570b4d8d0128e1943ae026aa689/cpp/OcvPersonDetection/PersonDetection.cpp#L89)):*
> ```cpp
>         imshow_on = parameters["IMSHOW_ON"].toUInt();
>         output_image = parameters["OUTPUT_IMAGE"].toUInt();
>         output_base_path = parameters["OUTPUT_BASE_PATH"].toUtf8().constData();
> ```

Let's remove `output_image` and `output_base_path` too. If we're not writing videos to disk we shouldn't write images to disk either. If someone wants to debug this, they can use `imshow()`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-contrib-components/11)*

**Comment by brosenberg42** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[cpp/OcvPersonDetection/PersonDetection.cpp, line 390 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-contrib-components/11#-KqzP8-wVQOam6KudI7p:-Kr1mbRvZ2tSEfwpJ1Zn:b-896fix) ([raw file](https://github.com/openmpf/openmpf-contrib-components/blob/acad11eda855809d2fc353fc3ae33a1e309bd90c/cpp/OcvPersonDetection/PersonDetection.cpp#L390)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

I agree, we should remove it.
</blockquote></details>

Done.

---

*[cpp/OcvPersonDetection/PersonDetection.cpp, line 89 at r2](https://reviewable.io:443/reviews/openmpf/openmpf-contrib-components/11#-Kr1dn8a2dDRBoywyqPH:-Kr1mZhnSQFbem5y4J-y:b-896fix) ([raw file](https://github.com/openmpf/openmpf-contrib-components/blob/17aa673778b4d570b4d8d0128e1943ae026aa689/cpp/OcvPersonDetection/PersonDetection.cpp#L89)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Let's remove `output_image` and `output_base_path` too. If we're not writing videos to disk we shouldn't write images to disk either. If someone wants to debug this, they can use `imshow()`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-contrib-components/11)*

**Comment by jrobble** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-contrib-components/11)*

**Pull request merged**
